---
title: "[pagingAidan](index.qmd){{< iconify fxemoji:hibiscus size=10px >}}"
description: "toronto


[gitHub](https://github.com/aidanastridge) [linkedIn](https://www.linkedin.com/in/aidanastridge/) [x](https://x.com/aidanastridge) [email](mailto:astridgeaidan@gmail.com)   


[home](index.qmd) [blog](blog.qmd) [visuals](visuals.qmd) [works](works.qmd)"
---

It ain't hard to tell   
date: 2024-08-21  

I'm getting back on track. Over the last year I've been dealing with depression, and anxiety due to neurological issues I've had since I was a kid. I have always persevered through; I loved math and coding too much to give up.

 Unfortunately, when it comes to making connections, I wasn't so great. I tend to be quiet and not willing to ask for help. I have a Management Science degree, there is truth to the adage of "who you know over what you know." Though:
 
 I've made a friend from Toronto with decades of experience in the field of data science and database management; I've joined a JavaScript coding community where I'm helping with backend development; I've started participating in TidyTuesday and Kaggle competitions; And I've supported DataForGood and DataKind initiatives through data analysis.

 As always, I'm learning.

  Best,  
  Aidan